### PR TITLE
Use `files` property in package.json

### PR DESCRIPTION
**Pull request by kevva**

### CODE REVIEW

**Comment by KenanY** [comment]
Should add `LICENSE` too.

**Comment by kevva** [comment]
Alright, fixed.

**Comment by kevva** [comment]
Actually, `license` is included by default too.

**Comment by kevva** [comment]
ping @maxogden.

**Comment by maxogden** [comment]
just curious why you need this?

**Comment by kevva** [comment]
Well, you could argue that the test files aren't that big, but I and a fair share of other projects are using this module and reducing the number of files upon install might speed up things, although by a little. Not super important anymore though since npm is doing great stuff caching and soon deduping dependencies.

**Comment by sindresorhus** [comment]
:+1: As I use this module a lot and want to keep my total dependency size to a minimum.

**Comment by shinnn** [comment]
+1

**Comment by maxogden** [comment]
cool, out as 1.4.9

**Comment by shinnn** [comment]
Thanks for merging, and concat-stream!

**Comment by kevva** [comment]
lol, nice.

**Pull request merged**
